# Generated by Django 5.0.6 on 2024-09-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
