# Generated by Django 5.0.6 on 2024-09-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_follower_profile_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
