# Generated by Django 5.0.6 on 2024-09-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
